name: 'record-store-spring'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    hostname: mysql
    command: --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - .docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: recsto
      MYSQL_USER: recsto
      MYSQL_PASSWORD: recsto
    ports:
      - "3306:3306"

  # The Spring boot app
  app:
    hostname: app
    stdin_open: true
    tty: true
    build:
      dockerfile: ./.docker/java/Dockerfile
      context: .
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - build/
            - .gradle/
        - action: rebuild
          path: build.gradle
