spring.application.name=recordstore

spring.mustache.prefix = classpath:/templates/
spring.mustache.suffix = .mustache

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:${DATABASE_URL}
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true